### ISSUE TITLE
Style guide: Single line declartion discrepancy

### ISSUE THREAD

**Issue by nathanrodger** [cwel-team/cwel#10]
When using a media query that only includes a sinlge rule, is it worth keeping that on multiple lines for readablity?

**Current**
`@include breakpoint('md') { width: auto; }`

**Suggested**
`@include breakpoint('md') {` 
&nbsp;&nbsp;&nbsp;&nbsp;`width: auto;`
 `}`

**Comment by dstuessy** [comment]
I would say inline. I will amend the [readme](https://github.com/cwel-team/cwel/blob/docs/code-guidelines/readme/scss-styleguide.md)

Edit: issue elaborated
