### ISSUE TITLE
Style guide: Variable name syntax discrepancy

### ISSUE THREAD

**Issue by nathanrodger** [cwel-team/cwel#11]
How would you define naming a variable that is not a component but a modifier or element of a parent block?

**Comment by dstuessy** [comment]
Given an example for context:

```
// icons
$c_icon_color_1: $c_primary;

// Button icons 
$c_buttonIcon_color_1: $white;
$c_buttonIcon_color_2: $c_primary; 
```

I would suggest writing button icon variables like this:

`$c_icon_button_color_1`
