### ISSUE TITLE
Style guide: Variable name syntax discrepancy 2

### ISSUE THREAD

**Issue by nathanrodger** [cwel-team/cwel#12]
When writing variables how should they be defined if  the same color is used twice? Would we group the color and use the one variable or create two variables?

**Example**
``` 
.button--secondary.button--on-light & path {
        fill: $c_icon_button_color_2;
        stroke: $c_icon_button_color_2;
} 
```

**Comment by dstuessy** [comment]
I would say it depends on the degree to which you want to template a component. If in your example you want to change both `fill` and `stroke` CSS properties separately, then you'd have two separate variables.
